---
title: "SMS Spam Detection with Naive Bayes"
description: "A text analysis project"
author:
  - name: "Longxiang Wu"
date: 2025-8-30
output:
  distill::distill_article:
    self_contained: false
---
---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.19.1
  kernelspec:
    display_name: Python 3 (ipykernel)
    language: python
    name: python3
---

```{r setup, include=FALSE}
library(reticulate)
use_python("/Users/Zhuanz/anaconda3/bin/python3.11", required = TRUE)
# or use your conda environment
use_condaenv("base", required = TRUE)
```

<!-- #region -->


With the rise in global mobile phone usage, a new avenue for creating spam emails has opened up in the notoriously aggressive marketing world. These advertisers exploit SMS text messaging to target potential consumers, sending them unwanted ads — i.e., spam texts. This type of spam is particularly troublesome because, unlike email spam, many mobile users are charged for every text message they receive. Developing a classification algorithm that can filter spam texts would provide a very useful tool for mobile carriers.

Since Naive Bayes has already been successfully applied to email spam filtering, it is likely applicable to SMS spam filtering as well. However, compared to email spam, automatic filtering of SMS spam presents additional challenges. Since texts are typically limited to 160 characters, the amount of text available to determine whether a message is spam is reduced. Combined with the inconvenience of a mobile keyboard, many people use SMS shorthand, which further blurs the line between legitimate and spam messages. Let's look at how a simple Naive Bayes classifier handles the challenges posed by these issues.

### 1 Collecting Data

To train our Naive Bayes classifier, we will use adapted spam SMS data collected from a website.

> For more information about the SMS spam dataset, refer to the paper published by the authors:
> *On the Validity of a New SMS Spam Collection* by J.M. Gomez Hidalgo, T.A. Almeida and A. Yamakami
> in Proceeding of the 11th IEEE International Conference on Machine Learning and Applications (2012).

The dataset contains the text content of SMS messages along with labels indicating whether each message is spam or not. Spam messages are labeled as **spam** and legitimate messages are labeled as **ham**. Below are some examples of both spam and ham messages.

Examples of **ham** (non-spam) messages:

> Better. Made up for Friday and stuffed myself like a pig yesterday. Now I feel bleh. But at least its not writhing pain kind of bleh.
>
> If he started searching he will get job in few days. He have great potential and talent.
>
> I got another job! The one at the hospital doing data analysis or something, starts on monday! Not sure when my thesis will got finished.

Examples of **spam** messages:

> Congratulations ur awarded 500 of CD vouchers or 125 gift guaranteed & Free entry 2 100 wkly draw txt MUSIC to 87066
>
> December only! Had your mobile 11mths+? You are entitled to updata to the latest colour camera mobile for Free! Call The Mobile Update Co FREE on 08002986906
>
> Valentines Day Special! Win over $1000 in our quiz and take your partner on the trip of a lifetime! Seng GO to 83600 now. 150/pmsg rcvd.

Looking at the SMS examples above, did you notice any obvious characteristics of spam messages? On one hand, a notable feature is that 2 out of 3 spam messages use the word "free", yet this word does not appear in any of the ham messages. On the other hand, compared to spam, 2 out of 3 ham messages reference a specific day of the week, while none of the spam messages do.

Our Naive Bayes classifier will exploit these kinds of word pattern advantages to determine whether an SMS is more likely spam or ham. While it's conceivable that the word "free" could appear in a ham message, a legitimate text is likely to provide additional context. For example, a ham message might say "are you free on Sunday?", while a spam message might say "free ringtones". The Naive Bayes classifier will calculate the probability of spam vs. ham based on the evidence provided by all the words in the message.

### 2 Exploring and Preparing the Data

The first step in building a classifier involves processing and analyzing the raw data. Preparing text data is challenging because converting words and sentences into a form that a machine can understand is essential. We will transform the data into a representation called a **bag-of-words (BOW)**, which ignores the order in which words appear and simply provides a variable to indicate whether each word is present.

> To make the data convenient to use in Python, the data used here has been modified from the original.
> If you want to follow along with this example, you can download the `sms_spam.csv` file from the website
> and save it to your Python working directory.

We will first use the `read_csv()` function from the pandas library to import the CSV data and store it in a DataFrame named `sms_raw`.

```{python}
import pandas as pd
sms_raw = pd.read_csv("sms_spam.csv", encoding="latin-1")
```

Using the descirbe() method in DataFrame, it can be seen that the sms_raw data file contains 5,567 text messages, and each text message has two variables: type and text. Among them, the variable type of SMS is encoded as ham or spam, while the variable text stores the entire SMS text.

```{python}
sms_raw.describe()
sms_raw.dtypes
```

The current feature type is a string vector. Since it is a classified variable, converting it into a factor variable will be conducive to subsequent data processing, of which 1 represents spam text messages and 0 represents non-spam text messages, as shown in the following code:

```{python}
sms_raw['type'] = pd.Series(sms_raw['type'].factorize()).iloc[0]
```

Observing the distribution of variable type, it can be seen that 745 (about 13%) text messages in the data set are marked as spam, and the rest of the text messages are marked as ham.

```{python}
sms_raw.groupby('type').count()
```

Now, let's not study the variable text. You will learn in the next section, because processing original text messages requires a new set of powerful tools dedicated to processing text data.

### 3 Data preparation - processing and analysing text data

A text message is a string of text composed of words, spaces, numbers and punctuation marks. Dealing with this type of complex data requires a lot of thinking and work. On the one hand, it needs to consider how to remove numbers and punctuation marks, how to deal with meaningless words, such as and, but and or, and how to decompose sentences into single words. Fortunately, these functions are already included in Python's sklearn library.

You can install the scikit-learn package by commanding `pip install scikit-learn`, and apply the command `import sklearn` to load it.

The first step in processing text data involves creating a corpus, that is, a collection of text files. In our example, a text file refers to a text message. We use the following command to build a corpus containing text messages in the training data.

```{python}
import string
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import CountVectorizer
from wordcloud import WordCloud
from sklearn import metrics
```

### Data preprocessing

The corpus now contains the original text content of 5,568 text messages. Before breaking down the text content into words, we need to take some cleaning steps to remove punctuation marks and other characters that may affect the result. For example, we will use the words hello!, HELLO and Hello as samples of the words hello.

First of all, we use the map method to remove punctuation marks and numbers in the text content, and convert all the strings in the text into lowercase:

```{python}
def tolower(text):
    return text.lower()

def removePunctuation(text):
    remove_chars = string.punctuation + '1234567890'
    table = str.maketrans('', '', remove_chars)
    return text.translate(table)

sms_raw['text'] = sms_raw['text'].map(removePunctuation).map(tolower)
```

When analysing text data, a common practice is to remove filler words, such as to, and, but and or, which are called stop words. We will use the `CountVectoriser` method in the `sklearn` package to remove stop words and calculate the word frequency distribution of the text:

```{python}
count_vect = CountVectorizer(stop_words="english",decode_error='ignore')
sms_counts = count_vect.fit_transform(sms_raw['text'])
sms_counts.shape
```

Due to the high medium dimension of the original word frequency matrix, we consider using TF-IDF for feature extraction, setting the minimum word frequency to 5, and extracting a total of 1489 variables.

```{python}
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vect = TfidfVectorizer(stop_words="english",decode_error='ignore',min_df=5)
sms_tfidf = tfidf_vect.fit_transform(sms_raw['text'])
sms_tfidf.shape
```

### Establish training data sets and test data sets

Since the data has been prepared for analysis, we now need to divide the data into training data sets and test data sets, so that we can apply the spam text message classifier to data that has not been studied before, and evaluate the performance of the classifier accordingly. We divide the data into two parts: 75% of the training data and 25% of the test data. Because the sorting of text messages is random, we can simply take the first 4176 text messages for training, and the remaining 1391 for testing.

```{python}
sms_trainx = sms_tfidf[0:4175,]
sms_trainy = sms_raw['type'][0:4175]
sms_testx = sms_tfidf[4176:5567,]
sms_testy = sms_raw['type'][4176:5567]
```

### Visualised text data - word cloud

Word cloud is a way to visualise the frequency of words appearing in text data. The word cloud is composed of words randomly distributed in the word cloud diagram. Words that often appear in the text will be presented in larger fonts, while less common words will be presented in smaller fonts. Recently, this type of picture has become more and more popular because it provides a way to observe hot topics on social media sites.

The wordcloud package provides a simple function to create this type of graphic, and we will apply this function to visualise the word types in the text message. Comparing the word clouds of spam text messages and non-spam text messages will help us understand whether the simple Bayes SMS filter is likely to succeed.

```{python}
wc = WordCloud()
wc.generate(' '.join(sms_raw['text']))
plt.imshow(wc, interpolation='bilinear')
plt.axis('off')
plt.show()
```

```{python}
wc = WordCloud()
wc.generate(''.join(sms_raw['text']))
plt.imshow(wc)
plt.show()
```

```{python}
wc.generate(''.join(sms_raw['text'][sms_raw['type']==1]))
plt.imshow(wc)
plt.show()
```

```{python}
wc.generate(''.join(sms_raw['text'][sms_raw['type']==0]))
plt.imshow(wc)
plt.show()
```

The word cloud obtained is displayed in the two graphics above. Do you have an intuition about which picture represents spam text messages and which picture represents non-spam text messages?

> Because it is a randomised processing, each word cloud may look slightly different. You can choose the most satisfactory word cloud by running the wordcloud() function many times, so as to achieve the purpose of demonstration.

Have you guessed that the graphic on the left is the word cloud of spam text messages? Spam text messages include words such as urgent, free, mobile, call, claim and stop, and these words have never appeared in non-spam text messages. On the contrary, the words used in non-spam text messages include can, sorry, need and time. These obvious differences show that our simple Bayesian model will have some powerful keywords to distinguish categories.


### 4 Data-based training model

Because we have converted the original text message into a form that can be represented by a statistical model, it is time to apply the simple Bayesian algorithm. The algorithm will count the probability of whether a given text message is a spam text message based on the existence of words.

We use the simple Bayes algorithm in the sklearn package to realise it.

```{python}
from sklearn.naive_bayes import MultinomialNB
sms_classifier = MultinomialNB().fit(sms_trainx,sms_trainy)
```

### 5 Evaluate the performance of the model

In order to evaluate the SMS classifier, we need to check the predicted value of the classifier based on the unknown text messages in the test data. Recall that unknown SMS characteristics are stored in a matrix called sms_testx, while the classification tags spam and ham are stored in sms_testy. We name the trained classifier sms_classifier. We will use it to generate the predicted value and compare the predicted value with the real value.

```{python}
# Predict the sample of the test set
sms_test_pred = sms_classifier.predict(sms_testx)
metrics.confusion_matrix(sms_testy, sms_test_pred)
```

It can be seen from the table that 3 out of 1209 non-spam text messages were mistakenly classified as spam text messages, with a proportion of 0.2%, while 32 out of 182 spam text messages were mistakenly classified as non-spam text messages, with a proportion of 17%. Considering that we have done almost nothing in this case, it is quite good to have this level of performance. In addition, the study of this case also explains why the simple Bayesian algorithm is a standard algorithm for text classification, and the simple Bayesian method can be used directly, and the execution effect is surprisingly good.

On the other hand, the 32 text messages that are mistakenly classified as spam text messages may bring significant problems to the deployment of filtering algorithms. If the filter causes someone to miss an important date or an emergency text message, they will quickly give up the product, so we need to study these misclassified text messages to see what's wrong.

Finally, we observed the classification index of the model and found that the accuracy and recall rate of the simple Bayes model reached 97%, indicating that the model we built could identify spam messages well.

```{python}
print(metrics.classification_report(sms_testy,sms_test_pred))
```



