---
title: "What is Fast Fourier Transformation?"
description: |
  A method of calculating the Fourier transform of a set of observations.
author:
  - name: Longxiang Wu
    url: https://lunghsiang-wu.github.io/longxiangwu/
date: 2025-04-09
preview: FFT-algorithm-1024x472.png
output:
  distill::distill_article:
    self_contained: false
    includes:
      in_header: header.html
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

A method of calculating the Fourier transform of a set of observations $x_0, x_1, \ldots, x_{n-1}$, i.e. calculating $d(\omega_p)$ given by

$$d(\omega_p) = \sum_{t=0}^{n-1} x_t e^{i\omega_p t}, \quad p = 0, 1, 2, \ldots, n-1; \quad \omega_p = \frac{2\pi p}{n}$$

The number of computations required to calculate $\{d(\omega_p)\}$ is $n^2$ which can be very
large. The FFT reduces the number of computations to $O(n \log_2 n)$, and operates in the
following way.

Let $n = rs$ where $r$ and $s$ are integers. Let $t = rt_1 + t_0$, $t = 0, 1, 2, \ldots, n-1$;
$t_1 = 0, 1, 2, \ldots, s-1$; $t_0 = 0, 1, 2, \ldots, r-1$. Further let $p = sp_1 + p_0$,
$p_1 = 0, 1, 2, \ldots, r-1$, $p_0 = 0, 1, \ldots, s-1$. The FFT can now be written

$$\begin{aligned}
d(\omega_p) = \sum_{t=0}^{n-1} x_t e^{i\omega_p t} &= \sum_{t_0=0}^{r-1} \sum_{t_1=0}^{s-1} x_{rt_1+t_0} e^{\frac{2\pi ip}{n}(rt_1+t_0)} \\
&= \sum_{t_0=0}^{r-1} e^{\frac{2\pi ip}{n}t_0} a(p_0, t_0)
\end{aligned}$$

where

$$a(p_0, t_0) = \sum_{t_1=0}^{s-1} x_{rt_1+t_0} e^{\frac{2\pi i t_1 p_0}{s}}$$

Calculation of $a(p_0, t_0)$ requires only $s^2$ operations, and $d(\omega_p)$ only $rs^2$. The evaluation of
$d(\omega_p)$ reduces to the evaluation of $a(p_0, t_0)$ which is itself a Fourier transform. Following
the same procedure, the computation of $a(p_0, t_0)$ can be reduced in a similar way. The
procedures can be repeated until a single term is reached. 

